### PR TITLE
[CCP-176] Root element is added correctly.

### PR DESCRIPTION
**Pull request by mkarthik90**
Previously pagination was added after root element. Just updated
the root element.

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
retest this please

**Comment by jdamerow** [comment]
The tests confirmed what I suspected. You broke any API method that used the ```getAllConceptEntries``` method.

**Comment by mkarthik90** [comment]
@jdamerow  Addressed review comments

**Pull request merged**
