### PR TITLE
Story/ccp 78

### PR DESCRIPTION
**Pull request by mkarthik90**
[CCP-78] Fixed review comments

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
Exception is thrown when deleting an entry:
image

Also, only concept wrapper and new concepts should be deletable. Not WordNet concepts (concepts for which wordnet id and concept id are the same).

**Comment by jdamerow** [comment]
retest this please

**Comment by jdamerow** [comment]
test this please

**Comment by jdamerow** [comment]
please resolve conflicts

**Comment by mkarthik90** [comment]
@jdamerow  Merge conflicts resolved and fixed few issues in edit functionality

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
The following needs to be changed:
1. Wordnet concepts should not have a delete button (because you can't delete them). Right now, there is a button but when I click it nothing happens.
2. Clicking on the delete button for a concept that can be deleted, it should direct to the delete page like when you delete a concept from the concept list view.

**Comment by mkarthik90** [comment]
@jdamerow  

1. Actually for deleting wornet concepts I have given a tooltip stating wordnet concepts cannot be deleted. So instead now there should not be any icon for that row am I right?

**Comment by jdamerow** [comment]
jup, correct. either no button or disabling it (with a tooltip) is fine too.

**Pull request closed without merging**
