### PR TITLE
Feature/ccp 195  Fix: Default value of numberOfRecordsPerPage is getting overridden

### PR DESCRIPTION
**Pull request by kkrish39**

### CODE REVIEW

**Comment by jdamerow** [comment]
for the future, please reopen your previous PR to keep the discussion.

**Comment by jdamerow** [comment]
test this please

**Comment by jdamerow** [comment]
run integration tests please

**Comment by jdamerow** [comment]
Jenkins, run integration tests please

**Comment by jdamerow** [comment]
integration tests are failing

**Comment by kkrish39** [comment]
I've pushed the Integration test fixes.

**Comment by kkrish39** [comment]
"No Record" test case is failing in jenkins. But it's getting passed in local.

**Comment by jdamerow** [comment]
Jenkins, run integration tests please

**Comment by jdamerow** [comment]
test this please

**Pull request merged**
