### PR TITLE
[CCP-170] Description will not be escaped anymore

### PR DESCRIPTION
**Pull request by mkarthik90**
Description was not appearing properly in UI. HTML tags
were escaped and rendered as normal string. From now on
all html tags will be rendered properly for description alone.

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
I made a fix for this a while ago as hotfix to master, but the changes must have been lost when the classes got moved. I also fixed the leading line break in descriptions of wordnet wrappers. Please apply that fix here as well:
https://github.com/diging/conceptpower/blob/026e1b4de1d939c6e5de1bbd3be53a4e7817b7c3/Conceptpower%2BSpring/src/main/java/edu/asu/conceptpower/wrapper/impl/ConceptEntryWrapperCreator.java

**Comment by mkarthik90** [comment]
@jdamerow  I checked the blame for ConceptEntryWrapperCreator. I am not able to find any changes on description. Is there any way I can check that.

**Comment by mkarthik90** [comment]
@jdamerow Added the description changes

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
description is empty now:
image

**Comment by jdamerow** [comment]
ok to test

**Pull request merged**
