### PR TITLE
Migrate from Db4o to MySQL

### PR DESCRIPTION
**Pull request by sri-9597**
# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
Migrate from Db4o to Mysql and spring data. This PR also includes changes to upgrade the java version to 17 and spring version to 6.0.9. The configuration has also been moved from xml based config to java based config  
## Anything else the reviewer needs to know?

The PR includes commits from earlier (Feb 2021). As the commits are pretty old,some changes have been made after upgrading to java 17 and spring 6 for compatibility.  Some custom properties to be defined are listed below: 

                <db.files.path></db.files.path>
		<email.server.host></email.server.host>
                <email.server.port></email.server.port>
                <email.username></email.username>
                <email.password></email.password>
                <email.from></email.from>
                <wordnet.install.path></wordnet.install.path>
		<db.user></db.user>
		<db.password></db.password>

### CODE REVIEW

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
I think there might be some changes in the pom.xml required?
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.2.2:war (default-war) on project conceptpower: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by sri-9597** [comment]
Make it so, Jenkins.

**Pull request closed without merging**
