### PR TITLE
Ccp 128

### PR DESCRIPTION
**Pull request by mkarthik90**
[CCP-128] Fixed user page issue

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
@mkarthik90, next time, please reopen the old PR, so that I see my previous comments. It should also built automatically if I told Jenkins to built it before.

**Comment by jdamerow** [comment]
Merging this. Improvements get their own tickets.

**Comment by jdamerow** [comment]
@mkarthik90, not sure if I adjusted the Jenkins job that builds develop. Please check http://diging.asu.edu:8081/conceptpower-test. If it breaks let Yogananda know to work on the review instance for now. Thanks.

**Comment by mkarthik90** [comment]
@jdamerow I will do that

**Pull request merged**
