### PR TITLE
Ccp 77

### PR DESCRIPTION
**Pull request by mkarthik90**
[CCP-77] Changes for edit button in concept search screen. Merged with [CCP-117]

### CODE REVIEW

**Comment by jdamerow** [comment]
please resolve conflicts

**Comment by mkarthik90** [comment]
@jdamerow  Resolved merge conflicts

**Comment by jdamerow** [comment]
can you merge develop into this branch please

**Comment by jdamerow** [comment]
Also, I just noticed that by default now "Adjective" is selected in the drop down under the search. That should be noun though.
image

**Comment by mkarthik90** [comment]
@jdamerow  I have used a HashMap instead of LinkedHashmap. I checked in the develop branch home screen and found that drop down ordering is as below with Verb selected by default. 


1) Verb
2) Adjective
3) Adverb
4) Noun

Could you please let me know the ordering of the drop down list. So that I will add accordingly in the linkedhashmap and fix this issue.

**Comment by jdamerow** [comment]
the ordering doesn't matter. but by default 'noun' should be selected.

**Comment by mkarthik90** [comment]
@jdamerow  I have made the changes and made sure Noun is selected by default. And if user searches for any concept. While displaying the search results the drop down will be selected with user selected pos.

**Comment by jdamerow** [comment]
retest this please

**Pull request merged**
