### PR TITLE
Story/ccp 117

### PR DESCRIPTION
**Pull request by mkarthik90**
[CCP-117] Resolved Merge conflicts and fixed the comments as per Review comments.

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
I get an error when trying to store a modified concept, is that in another story?

**Comment by jdamerow** [comment]
also, right now, I get an error alert when searching for a synonym in wordnet wrapper creation form:

image
 
if this is fixed in another branch, please just merge the branch into this one, and have one pull request for several tickets.

**Comment by mkarthik90** [comment]
@jdamerow  This was actually fixed but during merging i have missed something i guess. This is because while sending the JSON from controller I have used Word whereas in jsp i have tried with word. I will look into this and create a new PR.

**Pull request closed without merging**
