### PR TITLE
[CCP-204] Returned json string for all the error message.

### PR DESCRIPTION
**Pull request by mkarthik90**
Since the data is not returned as a json string, the error message were not
displayed correctly. From now on all the error message will be converted to a
json string and returned.

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
retest this please

**Comment by jdamerow** [comment]
retest this please

**Review by Mihika0409 — APPROVED** [review]

**Comment by jdamerow** [comment]
retest this please

**Comment by jdamerow** [comment]
there are a bunch of test failures, all failing with StreamCorruptedExceptions:
```
test_addConcept_noMatchingConceptType(edu.asu.conceptpower.rest.ConceptsTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.io.StreamCorruptedException: invalid stream header: 7B202277
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at edu.asu.conceptpower.rest.ConceptsTest.test_addConcept_noMatchingConceptType(ConceptsTest.java:260)
```

**Comment by jdamerow** [comment]
tests are still failing.

**Pull request closed without merging**
