### PR TITLE
Bug/CCP-226

### PR DESCRIPTION
**Pull request by mkarthik90**
Opened for testing integration tests

### CODE REVIEW

**Comment by mkarthik90** [comment]
run integration tests please

**Comment by mkarthik90** [comment]
@jdamerow  Changed the phrase query to term query because phrase query not fetching the values. And also while indexing the stop words shouldn't be removed to set the stop words to empty in Standard analyzer.

**Comment by jdamerow** [comment]
from the ticket: "let's make this optional; in rest interface there should be a flag to set, and gui interface there should be a checkbox or something."

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
There definitely needs to be a label for what this checkbox does, how would anyone know otherwise? Also, I'd put the checkbox under the input field.

**Comment by mkarthik90** [comment]
@jdamerow Addressed review comments

**Comment by jdamerow** [comment]
the search should be "or", eg.: 'einstein' in word OR 'einstein' in description

**Pull request closed without merging**
