### PR TITLE
[CCP-220] Used unescape from apache.

### PR DESCRIPTION
**Pull request by mkarthik90**
This will unescape the characters in all uris. But if the description field contains
a \", then this might not work. Not sure if the rest api call can contain a \" character.

### CODE REVIEW

**Comment by mkarthik90** [comment]
@jdamerow This will unescape the characters in all uris. But if the description field contains
a \", then this will not work. Not sure if the rest api call can contain a \" character.

**Comment by jdamerow** [comment]
why don't you just escape the fields that can contain uris (equals, similar to, etc)

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
Jenkins, run integration tests please

**Pull request merged**
