### PR TITLE
[CCP-168] Form will not be submitted when enter is pressed

### PR DESCRIPTION
**Pull request by mkarthik90**
Following changes are made to concept add screen.
1) When user does not enter any value for Term field
and tries to click on search, we do not hit the database,
instead we display error message.
2) In case of any error during ajax call we display
processing error to the user.
3) When user tries to search a word that is not in VIAF an
unknown alert box was appearing on the screen. Now handled
that condition by clearing the data table and displaying proper error
message.
4) Changed the button size to small to make it look better.

### CODE REVIEW

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
retest this please

**Comment by jdamerow** [comment]
Hm, hitting enter in the search box does still not search.

**Comment by mkarthik90** [comment]
@jdamerow  Added changes to make sure when enter is pressed on the search field, the term search happens. And when enter is pressed on other fields entire form gets submitted.

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
Since we're at it: when I hit enter in any other field the form gets submitted. If there are validation errors, the spinning icon for the search on top is continuously shown and spinning (which shouldn't be the case):
image

**Comment by mkarthik90** [comment]
screen shot 2016-09-21 at 11 39 31 am

**Comment by jdamerow** [comment]
ok to test

**Comment by mkarthik90** [comment]
@jdamerow  Fixed review comments

**Pull request merged**
